// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYNhtmfzylwTmOhJO7gizXZRwqzusjghI',
    appId: '1:818645806001:web:fb22c3ff54231e69beeb90',
    messagingSenderId: '818645806001',
    projectId: 'her2-adf12',
    authDomain: 'her2-adf12.firebaseapp.com',
    storageBucket: 'her2-adf12.firebasestorage.app',
    measurementId: 'G-L5W1V2MHQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxjeWfCOOspQReNkqr9tpS15TEIcGYih0',
    appId: '1:818645806001:android:eb39f2c5ad98e2b5beeb90',
    messagingSenderId: '818645806001',
    projectId: 'her2-adf12',
    storageBucket: 'her2-adf12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGXwxkijGhJJBmvdl0j5E0OsH62Kc2eRw',
    appId: '1:818645806001:ios:e2c275b7c59d6d47beeb90',
    messagingSenderId: '818645806001',
    projectId: 'her2-adf12',
    storageBucket: 'her2-adf12.firebasestorage.app',
    iosBundleId: 'com.example.her',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGXwxkijGhJJBmvdl0j5E0OsH62Kc2eRw',
    appId: '1:818645806001:ios:e2c275b7c59d6d47beeb90',
    messagingSenderId: '818645806001',
    projectId: 'her2-adf12',
    storageBucket: 'her2-adf12.firebasestorage.app',
    iosBundleId: 'com.example.her',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYNhtmfzylwTmOhJO7gizXZRwqzusjghI',
    appId: '1:818645806001:web:bbd4acc0d01e2de1beeb90',
    messagingSenderId: '818645806001',
    projectId: 'her2-adf12',
    authDomain: 'her2-adf12.firebaseapp.com',
    storageBucket: 'her2-adf12.firebasestorage.app',
    measurementId: 'G-STV56WT6MJ',
  );
}
